### ISSUE TITLE
"doctrine_cache.providers.apc_cache"

### ISSUE THREAD

**Issue by GitMostafaoui** [Happyr/GoogleAnalyticsBundle#8]
Hello everyone!
i configured a GoogleAnaliticsBundle and doctrineCacheBundle as saying in the documentatio of each bundle but i got this error:

  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "happyr.google.analytics.data_fetcher" has a dependency on a no
  n-existent service "doctrine_cache.providers.apc_cache".
any help will be aprecieted.

**Comment by Nyholm** [comment]
How does your configuration for DoctrineCacheBundle look like?

**Comment by GitMostafaoui** [comment]
Thanks a lot Nyhlom;
My config,yml is:
doctrine_cache:
  providers:
    file:
      file_system:
        extension: '.token'
        directory: '%kernel.root_dir%/var/storage/fs_cache/'
    my_apc_metadata_cache:
            type: apc
            namespace: metadata_cache_ns
    my_apc_query_cache:
            namespace: query_cache_ns
            apc: ~

**Comment by Nyholm** [comment]
With that configuration you got three services: 
* `doctrine_cache.providers.file`
* `doctrine_cache.providers.my_apc_metadata_cache`
* `doctrine_cache.providers.my_apc_query_cache`

Try with one of these instead of `doctrine_cache.providers.apc_cache`

**Comment by GitMostafaoui** [comment]
Thank you very much Nyhlom,
I will try those three services and you will find my answers here!
Many thanks.

**Comment by GitMostafaoui** [comment]
Sorry here is my 3 configurations of  happy_r google analitics  happy_r google_site_authntificator and doctrine_cache 
happyr_google_analytics:
    
    tracking_id: UA-XXXX-Y
    fetching:
        client_service: 'google.client.tobias_gmail'
        view_id: 0123456789
        cache_service: 'doctrine_cache.providers.apc_cache' # optinally a cache service
        cache_lifetime: 3600 # default
doctrine_cache:
  providers:
    file:
      file_system:
        extension: '.token'
        directory: '%kernel.root_dir%/var/storage/fs_cache/'
    my_apc_metadata_cache:
            type: apc
            namespace: metadata_cache_ns
    my_apc_query_cache:
            namespace: query_cache_ns
            apc: ~
happyr_google_site_authenticator:
  cache_service: 'doctrine_cache.providers.file'
  tokens:
    google_drive:
      client_id: '00000000000-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com'
      client_secret: 'xxxxx-xxxxx_xxxxxxxxxxxx'
      redirect_url: 'http://www.domain.com/admin/authenticate-google/return-url'
      scopes: ['https://www.googleapis.com/auth/drive']	
and the error now is:
ServiceNotFoundException: The service "happyr.google.analytics.data_fetcher" has a dependency on a non-existent service "doctrine_cache.providers.apc_cache".
How can i resolve this error?
Thanks a lot Nyhlom.

**Comment by Nyholm** [comment]
Replace the value that says `doctrine_cache.providers.apc_cache` with `doctrine_cache.providers.my_apc_metadata_cache`.

**Comment by GitMostafaoui** [comment]
Thanks Nylhom well received!
 i will try and i answer you here!

**Comment by GitMostafaoui** [comment]
Now i have this error:
ServiceNotFoundException: The service "happyr.google.analytics.data_fetcher" has a dependency on a non-existent service "google.client.tobias_gmail".

**Comment by GitMostafaoui** [comment]
Hello everyone:
I still have this error  when trying to put google.analitycs.bundle:
`ServiceNotFoundException: The service "happyr.google.analytics.data_fetcher" has a dependency on a non-existent service "google.client.tobias_gmail".`
i can't configure this bundle without kowing what that means??!!
Anyone can answer me?please!?
