### ISSUE TITLE
Bundle maintained

### ISSUE THREAD

**Issue by fcpauldiaz** [Happyr/GoogleAnalyticsBundle#9]
Is this bundle still maintained?

**Comment by Nyholm** [comment]
Yeah, But I've not been giving it a lot of love lately. Just found [my own PR](https://github.com/Happyr/GoogleAnalyticsBundle/pull/5) waiting to be merged since April. 

I do still use this bundle.

**Comment by fcpauldiaz** [comment]
Thanks for the reply, I will start using it then
